### ISSUE TITLE
Atributos disponíveis para o schema.json

### ISSUE THREAD

**Issue by reidark** [Edools/elegance#255]
Olá a todos,

Estou atualmente trabalhando em um projeto do EDools e gostaria de saber quais os atributos/chaves disponíveis para usar no arquivo "settings_data_schema.json".

No caso eu tenho interesse de criar um campo "datetime" ou pelo menos usar com uma máscara, mas não consegui nenhum resultado.

Quando eu tento usar o "type":  "datetime" ele não gera o input no painel.

`
{
        "key": "view.general.footer.testTime",
        "type": "datetime",
        "templateOptions": {
          "label": "Data e hora"
        }
}
`

**Comment by mandado** [comment]
boa tarde @reidark, Tranquilo ? 

Então, no painel usamos esse cara `http://angular-formly.com/#!/` para gerar os campos.

Dai os campos que aparecerão são os que a biblioteca dá suporte.

**Comment by reidark** [comment]
Obrigado @mandado, verificarei a documentação dessa lib.
